wordpress:
  image: wordpress
  ports:
   - "80:80"
  links:
   - mysql
  environment:
   - MYSQL_ROOT_PASSWORD=my-secret-pw
  volumes:
   - /usr/local/wp-content:/var/www/html/wp-content
mysql:
  image: mariadb
  environment:
   - MYSQL_ROOT_PASSWORD=my-secret-pw
  volumes:
   - /var/lib/mysql:/var/lib/mysql
