- name: CloudCompose Playbook
  hosts: all
  remote_user: root

  vars:
    - base_url: https://raw.githubusercontent.com/vpetersson/cloudcompose/master/example/
    - project: cloudnet
    - compose_file: /root/docker-compose.yml
    - retry_period: 5

  roles:
    - system
    - docker.ubuntu
    - cloudcompose
